# 워크플로우의 이름
name: Notion Content Revalidation

# 워크플로우가 언제 실행될지를 정의
on:
  # 1. 15분마다 자동으로 실행 (cron 스케줄)
  schedule:
    # cron 문법: 분 시 일 월 요일 (UTC 기준)
    # '*/15'는 '매 15분마다'를 의미합니다.
    - cron: "*/15 * * * *"

  # 2. 수동으로 실행할 수 있도록 버튼 추가 (선택 사항)
  workflow_dispatch:

jobs:
  # 'revalidate' 라는 이름의 작업 정의
  revalidate:
    # 이 작업이 실행될 가상 환경 지정
    runs-on: ubuntu-latest

    # 작업의 단계들
    steps:
      # 단계 1: 재검증 API 호출
      - name: Trigger ISR Revalidation
        # curl 명령어를 사용해 Next.js 블로그의 재검증 API에 POST 요청을 보냄
        # URL은 GitHub Secrets에 저장하여 보안을 유지
        run: curl -X POST "${{ secrets.REVALIDATE_URL }}"
